Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using prj1.Models;
using System.Web.Security;
using PagedList;

namespace prj1.Controllers
{
    [Authorize]
    public class MemberController : Controller
    {
        Entities db = new Entities();
        // GET: Member
        int pageSize = 5; //設定一頁顯示5筆資料
        public ActionResult Index(int page = 1)
        {
            int currentPage = page < 1 ? 1 : page;
            var pokemons = db.Tablepokemons1081640 //把所有寶可夢放進pokemons建立List
                .OrderBy(m => m.pId).ToList();
            var result = pokemons.ToPagedList(currentPage, pageSize);
            return View("../Home/Index", "_LayoutMember", result); //使用_LayoutMember頁面
        }

        public ActionResult Logout()
        {
            FormsAuthentication.SignOut();   // 登出
            return RedirectToAction("Login", "Home");
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Tablepokemons1081640 pokemon)
        {
            if (ModelState.IsValid)
            {
                ViewBag.Error = false;
                var temp = db.Tablepokemons1081640.Where(m => m.pId == pokemon.pId)
                    .FirstOrDefault();
                if (temp != null)
                {
                    ViewBag.Error = true;
                    return View(pokemon);
                }
                db.Tablepokemons1081640.Add(pokemon);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pokemon);
        }

        public ActionResult Edit(string pId)
        {
            var employee = db.Tablepokemons1081640
                .Where(m => m.pId == pId).FirstOrDefault();
            return View(employee);
        }

        [HttpPost]
        public ActionResult Edit(Tablepokemons1081640 pokemon)
        {
            if (ModelState.IsValid)
            {
                var temp = db.Tablepokemons1081640
                    .Where(m => m.pId == pokemon.pId)
                    .FirstOrDefault();
                temp.pName = pokemon.pName;
                temp.pType = pokemon.pType;
                temp.pLv = pokemon.pLv;
                temp.pHp = pokemon.pHp;
                temp.pAtk = pokemon.pAtk;
                temp.pDef = pokemon.pDef;
                temp.pSpeed = pokemon.pSpeed;
                temp.pMoves = pokemon.pMoves;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(pokemon);
        }

        public ActionResult Delete(string pId)
        {
            var pokemon = db.Tablepokemons1081640
                .Where(m => m.pId == pId).FirstOrDefault();
            db.Tablepokemons1081640.Remove(pokemon);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Pokemon Master</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("寶可夢大師之路", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("圖鑑", "Index", "Home")</li>
                    <li>@Html.ActionLink("註冊", "Register", "Home")</li>
                    <li>@Html.ActionLink("登入", "Login", "Home")</li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 成為寶可夢大師吧</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

Views/Shared/_LayoutMember.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Pokemon Master</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("寶可夢大師之路", "Index", "Member", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("圖鑑", "Index", "Member")</li>
                    <li>@Html.ActionLink("寶可夢新增", "Create", "Member")</li>
                    <li>@Html.ActionLink("登出", "Logout", "Member")</li>
                    <li><a href="#">@Session["Welcome"]</a></li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - 成為寶可夢大師吧</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.4.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>